# Generated by Django 4.2.7 on 2025-12-13 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academics', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableslot',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_slots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timetableslot',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='term',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='academics.academicyear'),
        ),
        migrations.AddField(
            model_name='subject',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='stream',
            name='class_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='academics.class'),
        ),
        migrations.AddField(
            model_name='class',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='academics.academicyear'),
        ),
        migrations.AddField(
            model_name='class',
            name='class_teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes_taught', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='class',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_years', to='tenants.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('tenant', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='stream',
            unique_together={('class_obj', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('tenant', 'academic_year', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='academicyear',
            unique_together={('tenant', 'name')},
        ),
    ]
