# Generated by Django 4.2.7 on 2025-12-13 13:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='Used in subdomain', unique=True)),
                ('code', models.CharField(help_text='School code/registration number', max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Invalid Zimbabwe phone number', regex='^\\+?263\\d{9}$')])),
                ('address', models.TextField()),
                ('city', models.CharField(default='Harare', max_length=100)),
                ('province', models.CharField(default='Harare', max_length=100)),
                ('school_type', models.CharField(choices=[('primary', 'Primary School'), ('secondary', 'Secondary School'), ('combined', 'Combined (Primary & Secondary)')], default='combined', max_length=20)),
                ('established_year', models.IntegerField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='tenants/logos/')),
                ('subscription_plan', models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('premium', 'Premium'), ('enterprise', 'Enterprise')], default='free', max_length=50)),
                ('subscription_start', models.DateField(blank=True, null=True)),
                ('subscription_end', models.DateField(blank=True, null=True)),
                ('max_students', models.IntegerField(default=100)),
                ('max_teachers', models.IntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('timezone', models.CharField(default='Africa/Harare', max_length=50)),
                ('language', models.CharField(choices=[('en', 'English'), ('sn', 'Shona'), ('nd', 'Ndebele')], default='en', max_length=10)),
            ],
            options={
                'db_table': 'tenants',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TenantSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('attendance_required', models.BooleanField(default=True)),
                ('late_arrival_threshold', models.IntegerField(default=15, help_text='Minutes after start time')),
                ('grading_scale', models.CharField(choices=[('percentage', 'Percentage (0-100)'), ('letter', 'Letter Grade (A-F)'), ('points', 'Points')], default='percentage', max_length=20)),
                ('sms_enabled', models.BooleanField(default=True)),
                ('whatsapp_enabled', models.BooleanField(default=False)),
                ('email_notifications', models.BooleanField(default=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('payment_gateway', models.CharField(choices=[('ecocash', 'EcoCash'), ('paynow', 'Paynow'), ('bank', 'Bank Transfer'), ('manual', 'Manual/Cash')], default='manual', max_length=50)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='tenants.tenant')),
            ],
            options={
                'db_table': 'tenant_settings',
            },
        ),
    ]
